// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAy9phS439lW6EjYpb7ID_1AvRDgnyEok',
    appId: '1:317087152711:web:3f0e7b35a0a83b00550f62',
    messagingSenderId: '317087152711',
    projectId: 'citytell',
    authDomain: 'citytell.firebaseapp.com',
    storageBucket: 'citytell.appspot.com',
    measurementId: 'G-9JBSKJC026',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTFdlhozTTXS7aKS1DY5zrQqGG6eZov0',
    appId: '1:317087152711:android:c0e14d342a8a646d550f62',
    messagingSenderId: '317087152711',
    projectId: 'citytell',
    storageBucket: 'citytell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPDUJ2v7pF-X8JrX8yV3Kr4STXU1lTAA',
    appId: '1:317087152711:ios:b4b8c08c0d424fdf550f62',
    messagingSenderId: '317087152711',
    projectId: 'citytell',
    storageBucket: 'citytell.appspot.com',
    androidClientId: '317087152711-lmscc2afpb5v1g6085jm1g6u700lc4mb.apps.googleusercontent.com',
    iosClientId: '317087152711-f1ue4as6d33jca9j8l36in9ds7qr3jmu.apps.googleusercontent.com',
    iosBundleId: 'com.ios.tello',
  );
}
